- djangocms_admin_style/sass/partials/_changelist.scss
- djangocms_admin_style/static/djangocms_admin_style/css/djangocms-admin.css
- updates filter button styles
- updates search icon size
before:
after:
> admin-styles filter button styles

- djangocms_admin_style/sass/partials/_forms.scss
- djangocms_admin_style/static/djangocms_admin_style/css/djangocms-admin.css
- https://divio-ch.atlassian.net/browse/CMS-327
- Please ignore compiled css file
Before:
After:
> fix view and width of form row plugin

- djangocms_admin_style/sass/components/_base.scss
- djangocms_admin_style/sass/components/_changelist.scss
- djangocms_admin_style/sass/components/_content.scss
- djangocms_admin_style/sass/mixins/_custom.scss
- djangocms_admin_style/sass/settings/_custom.scss
- djangocms_admin_style/static/djangocms_admin_style/css/djangocms-admin.css
- https://divio-ch.atlassian.net/browse/CMS-319
- please ignore compiled css file
> CMS-319 fixes and updates description and p styles

- djangocms_admin_style/sass/components/_base.scss
- djangocms_admin_style/sass/components/_changelist.scss
- djangocms_admin_style/sass/components/_content.scss
- djangocms_admin_style/sass/components/_forms.scss
- djangocms_admin_style/static/djangocms_admin_style/css/djangocms-admin.css
- https://divio-ch.atlassian.net/browse/CMS-324
- please ignore compiled css file
> CMS-324 show hide

- djangocms_admin_style/templates/admin/inc/branding.html
- https://divio-ch.atlassian.net/browse/CMS-351
Before:
After:
> CMS-351 Logout Screen

- djangocms_admin_style/templates/admin/inc/branding.html
- https://divio-ch.atlassian.net/browse/CMS-466
> updates variable name to get site name

- djangocms_admin_style/static/js/base-admin.js
- fix undefined elements after clicking on html
> fix native javascript menu error

- djangocms_admin_style/templates/admin/inc/branding.html
As proposed on the django-cms irc channel.
> Changing duoble qoute and single qoute order

- djangocms_admin_style/sass/components/_tables.scss
> Fix overlap between inline change link icon and text

- CHANGELOG.rst
- adds 1.0.7 for unreleased changes into changelog
> updates changelog

- CHANGELOG.rst
- gulpfile.js
- package.json
- https://github.com/divio/djangocms-admin-style/issues/250
- adds sourcemaps to gulpfile
> updates gulpfile

- djangocms_admin_style/sass/components/_login.scss
- should fix #268 
- but this is untestet, as I don't want to install the tool chain...
> Add the same style to #id_username and #id_password

- djangocms_admin_style/sass/components/_forms.scss
> adds pull request comment for #280

- CHANGELOG.rst
- djangocms_admin_style/templates/admin/base_site.html
instead of html, add it to body tag. 
fix for #307
> add body class djangocms-admin-style-enabled

- djangocms_admin_style/static/djangocms_admin_style/js/base-admin.js
|BEFROE|AFTER|
|---|---|
|![capture-for-jira-screenshot-20160402-125116-770](https://cloud.githubusercontent.com/assets/2270884/14707829/06722268-07c7-11e6-87e0-3fa0983259fd.png)|![screen shot 2016-04-21 at 13 42 48](https://cloud.githubusercontent.com/assets/2270884/14707834/095e9876-07c7-11e6-8db3-8c1e5154b9bf.png)|
> adds class hidden if toplinks are empty

- MANIFEST.in
> Remove .* files from manifest

- djangocms_admin_style/templates/admin/inc/branding.html
Since django 3.x doesn't support "sttaicfiles", Trying to replace it with "static", Locally it's working good.
> Changing "staticfiles" to "static"

- CHANGELOG.rst
- setup.cfg
> TASK: Add brackets around release date

- CHANGELOG.rst
- djangocms_admin_style/__init__.py
- setup.py
> Bump version to 3.2.4

- .github/PULL_REQUEST_TEMPLATE.md
This enhancement introduces a Pull Request Template inspired by the one used in the Django CMS repository.
* [Django CMS Pull Request template](https://github.com/django-cms/django-cms/blob/develop-4/.github/PULL_REQUEST_TEMPLATE.md)
> feat: Add Pull Request Template
